### ISSUE TITLE
Problem when resignFirstResponder is call

### ISSUE THREAD

**Issue by thomasccpereira** [filipstefansson/AutocompleteField#2]
Hi there!

I'm facing a problem when I call **self.view.endEditing(true)**, the autocomplete textField doesn't loose focus. I solved this behavior by changing your method (locally):

```
    public override func resignFirstResponder() -> Bool {
        self.label.text = nil
        super.resignFirstResponder() // add this line
        return true
    }
```

I'm the right way?
Thank you.

**Comment by filipstefansson** [comment]
Tried this in the new v2.0, and it seems to work. I'll close this issue since it's really old, and then we can open a new one if the problem still exists.
